__author__ = 'Eidan Wasser'

caseInfo = {
"test (General.CreateTask.CreateATask)": "C19603. General Features: Add task - quick add",
"test (General.EditTitle.EditTitle)": "C19604. General Features: Edit task title",
"test (General.Swipe.Swipe)": "C19605. General Features: Swipe task",
"test (General.Unswipe.Unswipe)": "C19606. General Features: Unswipe task",
"test (General.Delete.Delete)": "C19608. General Features: Delete task by pressing",
"test (General.RestoreFromDoneList.RestoreFromDeleted)": "C19609. General Features: Restore a task from done list",
"test (General.DeleteFromDoneList.DeleteFromDoneListOne)": "C19610. General Features: Check that task in Done list get deleted (One by one)",
"test (General.DeleteFromDoneListAll.DeleteFormDoneListAll)": "C19611. General Features: Check that task in Done list get deleted (All together)",
"test (General.PriorityHigh.PriorityHigh)": "C19612. General Features: Change priority to high",
"test (General.PriorityNormal.PriorityNormal)": "C19613. General Features: Change priority to normal",
"test (General.ChangeList.ChangeList)": "C19614. General Features: Change list of the task (from task options)",
"test (Lists.NewList.NewList)": "C19650. Lists: Add new list from + sign on main view",
"test (Lists.EditFromMain.EditMain)": "C19651. Lists: Edit list title: from  main screen",
"test (Lists.EditFromLongPress.EditFromLongPress)": "C19652. Lists: Edit list title: from list screen (long press)",
"test (Lists.EditFromOptions.EditFromOptions)": "C19653. Lists: Edit list title: from list screen (in options)",
"test (Lists.DeleteFromMain.DeleteMain)": "C19655. Lists: Delete list: from main screen",
"test (Lists.DeleteFromOptions.DeleteFromOptions)": "C19656. Lists: Delete list: from list view (in options)",
"test (Lists.DragAndDropList.DragAndDropList)": "C19658. Lists: Main grid - Rearrange lists",
"": "C19659. Lists: See that number of tasks in the list is the same as what's written in the main screen",
"": "C19660. Lists: See that number of tasks in all the different lists sum up to number of tasks in ALL",
"test (Views.PriorityHighAdd.PriorityHighAdd)": "C19616. Views: Priority view: add task to the STARRED section",
"test (Views.PriorityHighDrag.PriorityHighDrag)": "C19617. Views: Priority view: drag task from REGULAR to STARRED section",
"test (Views.PriorityNormalDrag.PriorityNormalDrag)": "C19618. Views: Priority view: drag task from STARRED to REGULAR section",
"test (Views.PriorityHighView.PriorityHighView)": "C19619. Views: Priority view: add priority to a task that's on the REGULAR section",
"test (Views.PriorityNormalView.PriorityNormalView)": "C19620. Views: Priority view: remove priority to a task that's on the STARRED section",
"test (Views.DateTomorrowDrag.DragTomorrow)": "C19622. Views: Date view: drag task between dates: Tomorrow",
"test (Views.DateUpcoming.Upcoming)": "C19623. Views: Date view: drag task between dates: Upcoming",
"test (Views.DateSomedayDrag.DragSomeday)": "C19624. Views: Date view: drag task between dates: Someday",
"test (Views.DateTodayAdd.TodayAdd)": "C19625. Views: Date view: add task in 'Tomorrow', add reminder (via quick add) for today",
"test (Subtasks.Add.Add)": "C19633. Subtasks: Add subtasks",
"test (Subtasks.Edit.Edit)": "C19634. Subtasks: Edit subtasks",
"test (Subtasks.Swipe.Swipe)": "C19635. Subtasks: Swipe subtasks",
"test (Subtasks.Unswipe.Unswipe)": "C19636. Subtasks: Unswipe subtasks",
"test (Subtasks.Delete.Delete)": "C19637. Subtasks: Delete subtasks",
"test (Files.AddPic.AddPic)": "C19627. Files: Upload image",
"test (Files.AddVideo.AddVideo)": "C19627. Files: Upload video",
"test (Files.AddAudio.AddAudio)": "C19627. Files: Upload audio",
"test (Files.GoogleDrive.GoogleDrive)": "C19627. Files: Upload from Google Drive",
"test (Files.PreviewPic.PreviewPic)": "C19629. Files: Preview image",
"test (Files.PreviewVideo.PreviewVideo)": "C19629. Files: Preview video",
"test (Files.DeletePic.DeletePic)": "C19628. Files: Delete image",
"test (Files.DeleteVideo.DeleteVideo)": "C19628. Files: Delete video",
"test (Files.DeleteAudio.DeleteAudio)": "C19628. Files: Delete audio",
"test (Files.AddNote.AddNote)": "C19630. Files: add note",
"test (Files.EditNote.EditNote)": "C19631. Files: Edit note",
"": "C19661. Recurrence - free: Daily Never",
"": "C19662. Recurrence - free: Weekly Never",
"": "C19663. Recurrence - free: Monthly Never",
"": "C19664. Recurrence - free: Yearly Never",
"": "C19665. Recurrence - free: Remove recurring",
"": "C19666. Recurrence - free: Drag to someday - all recurrences are removed",
"": "C19667. Recurrence - free: Edit from someday to be recurring",
"": "C19677. Recurrence - premium: Weekly: Repeat on multiple days",
"": "C19678. Recurrence - premium: Monthly: Repeat by day of the week",
"": "C19679. Recurrence - premium: Every X days, Y times",
"": "C19680. free user: see upsell screens (description)",
"": "C19649. purchase scenarios: new registered user - buy from upsell",
"": "C19668. sharing: Share task, accept on other side, Drag to tomorrow, upcoming, someday",
"": "C19669. sharing: Share task, accept on other side, Add priority, notes, reminder, subtasks, files at once",
"": "C19670. sharing: On above task - Decline invitation",
"": "C19671. sharing: On above task, make comments",
"": "C19640. List sharing: On a shared list - add task with priority, notes, subtasks, files, reminder",
"": "C19641. List sharing: Edit priority, notes, subtasks, files, reminder, task title",
"": "C19642. List sharing: Complete task on a shared list",
"": "C19643. List sharing: Move task from a private list to the shared list",
"": "C19644. List sharing: Move task from the shared list to a private list",
"": "C19676. Edit default folder: Set another folder as default (from settings), add task in ALL",
"": "C19645. Cross platform positioning: Main grid - reorder - see that list order syncs",
"": "C19646. Cross platform positioning: List view - Reorder tasks in a specific folder (check sync)",
"": "C19647. Cross platform positioning: List view - See that tasks are ordered in ALL (check sync)",
"": "C19638. Settings: Settings layout - Free user",
"": "C19639. Settings: Settings layout - Premium user",
"": "C19648. Settings: profile page - all buttons work",
"": "C19626. Settings: Change pic on current platform - validate it changed on other platforms",
"": "C19672. Install scenarios: login",
"": "C19673. Install scenarios: login w/ google",
"": "C19674. Install scenarios: login w/ FB (see that user pic. is taken)",
"test (Signup.SignUp)": "C19675. Install scenarios: register",
}
def get_info(testString):
    res = caseInfo[testString]
    return res